# Generated by Django 5.1 on 2024-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0002_alter_userdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
