# Generated by Django 5.1 on 2024-09-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0003_alter_userdata_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
