# Generated by Django 5.1 on 2024-09-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
