# Generated by Django 5.1 on 2024-09-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0011_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
    ]
