# Generated by Django 5.1 on 2024-09-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0012_remove_cart_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
    ]
