# Generated by Django 5.1 on 2024-09-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0014_finalorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
