# Generated by Django 5.1 on 2024-09-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0015_cart_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='finalorders',
            name='phone',
        ),
    ]
