# Generated by Django 5.1 on 2024-09-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0016_remove_finalorders_email_remove_finalorders_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalOrders',
        ),
    ]
