# Generated by Django 5.1 on 2024-09-22 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0017_delete_finalorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('order_details', models.JSONField()),
                ('phone', models.CharField(max_length=15)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('order_status', models.CharField(default='Confirmed', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
