# Generated by Django 5.1 on 2024-09-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0018_finalorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorders',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
