# Generated by Django 5.1 on 2024-09-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodify', '0019_alter_finalorders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorders',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
